apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ingressClassName: traefik
  rules:
    - host: audiobooks.edilab.org
      http:
        paths:
          - backend:
              service:
                name: audiobookshelf
                port: 3005
                  number: 
            path: /
            pathType: Prefix