apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:73rO7Nx8BVc8IvVJDV4V9qKGqnjR+EfGBwSbqn3xD5QqUOmQ34Jeid+42KwdtjN8n4Q6cQfFS7EeoA2r1Mjg8YU9IC7aZzQXKA8Tcne1P5W/yGnTQvhkvYqGYrZwJ2W7ZprhlXGRQCPP/TnJ+DXfMU2a0TKBySAnRLq91GADM3Y3TpS243c4RUIBdsK9dweZx1zfJcRtgonBlaRWtdPPSeiFXrGClTW6GSifn5xEuYmNHMhCNdZ0TaagXOxvKUI+pdf4yh2v1nNjm308zkxsq8RwKu3tLArzyZnBzlSY009srn2LgXUJJHRmpM0=,iv:DtUIQ/OMfggCEAH8uxo0+CMAEmIPFnhq8roXL1e2onI=,tag:aVkora7pSSVa1djiyBvWoQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1tkcj8acwcs9pgcp3k8xa9u5d9xlkwneeqq7arwt6kv6flnr8mylq627ver
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bGprVkNzeEl0SVRPdjRW
            eEd0dEFnaTZUOElodlo2Rk9YVmgyMDNPakhzCkR0OHMyUUlEa0wweklxT0szSU5p
            N0lKc28xSUl6cEE3T1FpNnNpclZIdHMKLS0tIERUZktHZ29ZVmxjZXJxbUZ0RHZ2
            RkxqZzF5dVF1bGRPZmN0UVpkZk1abFUKQfziGNklEGEXqQVpBNr0P3n4NA+O22Vj
            pHxqIJryyJP2tQW3tQ/MzCboqkkVTL7lS6ioNEuRTOhlcmdfo8jqug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T15:42:25Z"
    mac: ENC[AES256_GCM,data:z94cov++P/a/WRuf1KfW2K7LsTe/xA6yduoOdgxmWe8gg+SQqwRfP9Feee0ciB/COpd6vMMJ9YSk94aDpgNB8NaK+zptF85Th26n+p/a39FrSdtTZ6BSIwPm9o8hxd8bI5j4cBGWr88HdE6rgNy3q/lcd45GDNKVcY9xbs1MvLI=,iv:SaLZ7Xurhx2ezza7cNUKPfJ3MrDC8twraZT8CV8whJc=,tag:bxnvsXQ3tjJOLrRpI6Db8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
