apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:d/Zy,iv:5O0AXNYK7lAXP2eu3aBPgcWJT0TFZGaoWMdq5ezZ/Cc=,tag:KNQafXGCmDknY5Z3YwhEFg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:sxRufro7,iv:4TTkHiMYJW6mako9+dMfChsx7PhX9sGfnU+1kbDgUeM=,tag:d1l+A7uWt3hcMEFg4888PQ==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1tkcj8acwcs9pgcp3k8xa9u5d9xlkwneeqq7arwt6kv6flnr8mylq627ver
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTVRxQVV1SlhSVGhjeDMr
            dmhIdmJ2UC83cTZIN1hQaVFzWm80WGM1MmdVCmxPdk0yMXloWGtualVWTnNaMDMw
            ak1NVzR0Tjh2QXcxY3BwMVRUdlQ4encKLS0tIGVsaW1sTlY1NzRiVS96dWwySWR6
            aEN3R1R4STQrMmxTVmhPdFNpUnVCUWMKOgj97DS8FySQtNlqk1BFe9p9uD7mpTF/
            HTfZwQ3yJT0X3ajZOqvWebHjjpBudpMz+WFuKcXCnp9StBalv8kqcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T16:13:15Z"
    mac: ENC[AES256_GCM,data:WoD0dX6jOs833l4xiW9lLyIiyR5NoKGz3mj9ULJOPFeVHMM0YEgX+W4Vz2K1TKXvhyAzapvVJP2A0DFr4Pq37y4yjy5VtVZ5r/XexDTxUiGMGCeb1TTUucjjjeou5SIBzLnldK4hHpb8aQqozipmgyyCQ45ia+ADdf5AFKawzMw=,iv:CzPAePuibXejDy82Yn7+qGr7ThIcaG2KghFNbU+5sFA=,tag:0xixVNWQ+tN2jGOU4HcfeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
