apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Nbtx3w==,iv:v4QhZs1GOwdaZwI4W6TpUEu9gKfrAqnIOc7KI1n9Oec=,tag:uJ5a7KiiklGoyl8jTFIpuA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Iv31bY6gvZg=,iv:dVNBM3X6a6AKHO+Gv8plL+T0XHGCD8CQJPfPe2Qiu74=,tag:ukxyxxKrpleHiw1shtyL7A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1tkcj8acwcs9pgcp3k8xa9u5d9xlkwneeqq7arwt6kv6flnr8mylq627ver
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmxlbUorODZZYk9QdHho
            MTQ0UkoyelJLaHFleEIwZlQvY3R2Ujg5R0h3CllaNGlJN25WdjVJSVBjeTZ6emhG
            ZUMzQTFmOVg3Vkw2bldQS0JaUFpwdGcKLS0tIEx4emxvVkNFZzhNRENKK0themFZ
            cWhTdmR6S1V3TDlEMGVySDFDRTJHWXMKtEcHQgIpW5a0ga27pvWWJd0j8EK1RNp7
            dwj277VAqZlsJzwc/MP5JcUydgD02hbA1PbfLlV3A8ZyxLtTjnCLyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T16:52:05Z"
    mac: ENC[AES256_GCM,data:MIGoqzHNUthZ7IxJpu4aI5anFBEBbfCug3TeQSgksd37rGWkUTBOT4LRdrciKhkd/9b43RWk8LZEll2i5yJWSks0cPzNs6SVKRF3PRRoDdfPWbCq7uAJe0T0AWfY10mu4mj8mNZm35hFqHDE5+Du6x3KjODEtyw+GaN9MPvZbms=,iv:P2QfJXdSON/Z4qbQ8jvXdS5IFUssdVIygo4aLVXs49A=,tag:N07fF0b8NDpEPPnyApMHrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
