apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 34.2.1        # pin a version you trust
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    service:
      ipFamilyPolicy: PreferDualStack
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true

    service:
      ipFamilyPolicy: PreferDualStack

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true

