apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
        allowExternalNameServices: true

    service:
      ipFamilyPolicy: PreferDualStack

    ports:
      websecure:
        tls:
          enabled: true

    additionalArguments:
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

    deployment:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
