apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true

    service:
      ipFamilyPolicy: PreferDualStack

    ports:
      websecure:
        tls:
          enabled: true
