apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 34.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    # Make Traefik the default IngressClass so apps in any namespace work
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
        # optional but handy on k3s
        allowExternalNameServices: true

    service:
      ipFamilyPolicy: PreferDualStack
      # type: NodePort        # uncomment if you prefer NodePort over KlipperLB

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true

    deployment:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
